/* eslint-disable @typescript-eslint/no-var-requires */
module.exports = {
	content: ['./src/**/*.{html,svelte,js,ts}'],
	plugins: [require('@tailwindcss/typography'), require('daisyui')],
	theme: {
		extend: {
			/* boiler plate to use tailwind classes with those colors. (They are defined in app.pcss) */
			colors: {
				kingdom: 'hsl(var(--kingdom) / <alpha-value>)',
				subkingdom: 'hsl(var(--subkingdom) / <alpha-value>)',
				infrakingdom: 'hsl(var(--infrakingdom) / <alpha-value>)',
				superphylum: 'hsl(var(--superphylum) / <alpha-value>)',
				phylum: 'hsl(var(--phylum) / <alpha-value>)',
				subphylum: 'hsl(var(--subphylum) / <alpha-value>)',
				infraphylum: 'hsl(var(--infraphylum) / <alpha-value>)',
				superclass: 'hsl(var(--superclass) / <alpha-value>)',
				class: 'hsl(var(--class) / <alpha-value>)',
				subclass: 'hsl(var(--subclass) / <alpha-value>)',
				infraclass: 'hsl(var(--infraclass) / <alpha-value>)',
				superorder: 'hsl(var(--superorder) / <alpha-value>)',
				order: 'hsl(var(--order) / <alpha-value>)',
				suborder: 'hsl(var(--suborder) / <alpha-value>)',
				infraorder: 'hsl(var(--infraorder) / <alpha-value>)',
				pavorder: 'hsl(var(--pavorder) / <alpha-value>)',
				superfamily: 'hsl(var(--superfamily) / <alpha-value>)',
				family: 'hsl(var(--family) / <alpha-value>)',
				subfamily: 'hsl(var(--subfamily) / <alpha-value>)',
				tribe: 'hsl(var(--tribe) / <alpha-value>)',
				subtribe: 'hsl(var(--subtribe) / <alpha-value>)',
				genus: 'hsl(var(--genus) / <alpha-value>)',
				subgenus: 'hsl(var(--subgenus) / <alpha-value>)',
				species: 'hsl(var(--species) / <alpha-value>)',
				'kingdom-content': 'hsl(var(--kingdom-content) / <alpha-value>)',
				'subkingdom-content': 'hsl(var(--subkingdom-content) / <alpha-value>)',
				'infrakingdom-content': 'hsl(var(--infrakingdom-content) / <alpha-value>)',
				'superphylum-content': 'hsl(var(--superphylum-content) / <alpha-value>)',
				'phylum-content': 'hsl(var(--phylum-content) / <alpha-value>)',
				'subphylum-content': 'hsl(var(--subphylum-content) / <alpha-value>)',
				'infraphylum-content': 'hsl(var(--infraphylum-content) / <alpha-value>)',
				'superclass-content': 'hsl(var(--superclass-content) / <alpha-value>)',
				'class-content': 'hsl(var(--class-content) / <alpha-value>)',
				'subclass-content': 'hsl(var(--subclass-content) / <alpha-value>)',
				'infraclass-content': 'hsl(var(--infraclass-content) / <alpha-value>)',
				'superorder-content': 'hsl(var(--superorder-content) / <alpha-value>)',
				'order-content': 'hsl(var(--order-content) / <alpha-value>)',
				'suborder-content': 'hsl(var(--suborder-content) / <alpha-value>)',
				'infraorder-content': 'hsl(var(--infraorder-content) / <alpha-value>)',
				'pavorder-content': 'hsl(var(--pavorder-content) / <alpha-value>)',
				'superfamily-content': 'hsl(var(--superfamily-content) / <alpha-value>)',
				'family-content': 'hsl(var(--family-content) / <alpha-value>)',
				'subfamily-content': 'hsl(var(--subfamily-content) / <alpha-value>)',
				'tribe-content': 'hsl(var(--tribe-content) / <alpha-value>)',
				'subtribe-content': 'hsl(var(--subtribe-content) / <alpha-value>)',
				'genus-content': 'hsl(var(--genus-content) / <alpha-value>)',
				'subgenus-content': 'hsl(var(--subgenus-content) / <alpha-value>)',
				'species-content': 'hsl(var(--species-content) / <alpha-value>)'
			}
		}
	},
	daisyui: {
		themes: [
			/* Here we associate taxon color with the theme (simple swap depending on light and black). */
			{
				light: {
					...require('daisyui/src/theming/themes')['light'],
					primary: '#115e59',
					'primary-content': '#d0dddb',
					secondary: '#4f46e5',
					'secondary-content': '#e5dcff',
					accent: '#6ee7b7',
					neutral: '#4b5563',
					'neutral-content': '#9ca3af',
					'base-100': '#ffffff',
					info: '#3b82f6',
					success: '#84cc16',
					warning: '#facc15',
					error: '#ef4444',
					'--kingdom': 'var(--kingdom1)',
					'--kingdom-content': 'var(--kingdom2)',
					'--subkingdom': 'var(--subkingdom1)',
					'--subkingdom-content': 'var(--subkingdom2)',
					'--infrakingdom': 'var(--infrakingdom1)',
					'--infrakingdom-content': 'var(--infrakingdom2)',
					'--superphylum': 'var(--superphylum1)',
					'--superphylum-content': 'var(--superphylum2)',
					'--phylum': 'var(--phylum1)',
					'--phylum-content': 'var(--phylum2)',
					'--subphylum': 'var(--subphylum1)',
					'--subphylum-content': 'var(--subphylum2)',
					'--infraphylum': 'var(--infraphylum1)',
					'--infraphylum-content': 'var(--infraphylum2)',
					'--superclass': 'var(--superclass1)',
					'--superclass-content': 'var(--superclass2)',
					'--class': 'var(--class1)',
					'--class-content': 'var(--class2)',
					'--subclass': 'var(--subclass1)',
					'--subclass-content': 'var(--subclass2)',
					'--infraclass': 'var(--infraclass1)',
					'--infraclass-content': 'var(--infraclass2)',
					'--superorder': 'var(--superorder1)',
					'--superorder-content': 'var(--superorder2)',
					'--order': 'var(--order1)',
					'--order-content': 'var(--order2)',
					'--suborder': 'var(--suborder1)',
					'--suborder-content': 'var(--suborder2)',
					'--infraorder': 'var(--infraorder1)',
					'--infraorder-content': 'var(--infraorder2)',
					'--pavorder': 'var(--pavorder1)',
					'--pavorder-content': 'var(--pavorder2)',
					'--superfamily': 'var(--superfamily1)',
					'--superfamily-content': 'var(--superfamily2)',
					'--family': 'var(--family1)',
					'--family-content': 'var(--family2)',
					'--subfamily': 'var(--subfamily1)',
					'--subfamily-content': 'var(--subfamily2)',
					'--tribe': 'var(--tribe1)',
					'--tribe-content': 'var(--tribe2)',
					'--subtribe': 'var(--subtribe1)',
					'--subtribe-content': 'var(--subtribe2)',
					'--genus': 'var(--genus1)',
					'--genus-content': 'var(--genus2)',
					'--subgenus': 'var(--subgenus1)',
					'--subgenus-content': 'var(--subgenus2)',
					'--species': 'var(--species1)',
					'--species-content': 'var(--species2)'
				},
				dark: {
					...require('daisyui/src/theming/themes')['dark'],
					primary: '#d0dddb',
					'primary-content': '#115e59',
					secondary: '#e5dcff',
					'secondary-content': '#4f46e5',
					accent: '#6ee7b7',
					neutral: '#9ca3af',
					'base-100': '#374151',
					info: '#3b82f6',
					success: '#84cc16',
					warning: '#facc15',
					error: '#ef4444',
					'--kingdom': 'var(--kingdom2)',
					'--kingdom-content': 'var(--kingdom1)',
					'--subkingdom': 'var(--subkingdom2)',
					'--subkingdom-content': 'var(--subkingdom1)',
					'--infrakingdom': 'var(--infrakingdom2)',
					'--infrakingdom-content': 'var(--infrakingdom1)',
					'--superphylum': 'var(--superphylum2)',
					'--superphylum-content': 'var(--superphylum1)',
					'--phylum': 'var(--phylum2)',
					'--phylum-content': 'var(--phylum1)',
					'--subphylum': 'var(--subphylum2)',
					'--subphylum-content': 'var(--subphylum1)',
					'--infraphylum': 'var(--infraphylum2)',
					'--infraphylum-content': 'var(--infraphylum1)',
					'--superclass': 'var(--superclass2)',
					'--superclass-content': 'var(--superclass1)',
					'--class': 'var(--class2)',
					'--class-content': 'var(--class1)',
					'--subclass': 'var(--subclass2)',
					'--subclass-content': 'var(--subclass1)',
					'--infraclass': 'var(--infraclass2)',
					'--infraclass-content': 'var(--infraclass1)',
					'--superorder': 'var(--superorder2)',
					'--superorder-content': 'var(--superorder1)',
					'--order': 'var(--order2)',
					'--order-content': 'var(--order1)',
					'--suborder': 'var(--suborder2)',
					'--suborder-content': 'var(--suborder1)',
					'--infraorder': 'var(--infraorder2)',
					'--infraorder-content': 'var(--infraorder1)',
					'--pavorder': 'var(--pavorder2)',
					'--pavorder-content': 'var(--pavorder1)',
					'--superfamily': 'var(--superfamily2)',
					'--superfamily-content': 'var(--superfamily1)',
					'--family': 'var(--family2)',
					'--family-content': 'var(--family1)',
					'--subfamily': 'var(--subfamily2)',
					'--subfamily-content': 'var(--subfamily1)',
					'--tribe': 'var(--tribe2)',
					'--tribe-content': 'var(--tribe1)',
					'--subtribe': 'var(--subtribe2)',
					'--subtribe-content': 'var(--subtribe1)',
					'--genus': 'var(--genus2)',
					'--genus-content': 'var(--genus1)',
					'--subgenus': 'var(--subgenus2)',
					'--subgenus-content': 'var(--subgenus1)',
					'--species': 'var(--species2)',
					'--species-content': 'var(--species1)'
				}
			}
		]
	}
};
